### ISSUE TITLE
use cfconfig to create Oracle datasource

### ISSUE THREAD

**Issue by bardware** [Ortus-Solutions/cfconfig#12]
Hi,

I call
```
cfconfig datasource save name=datasource dbdriver=oracle host=XXXHOSTXXX SID=XXXSIDXXX port=1521 da
tabase=XXXDBXXX username=XXXUSERXXX password=XXXPWDXXX
```
on the `box` command line. Then I export the settings to a `.json` file and read the line 
```
"dsn":"jdbc:macromedia:oracle://Server:1521;AuthenticationMethod=userIDPassword;sendStringParametersAsUnicode=false;querytimeout=0;MaxPooledStatements=100",
```
I cannot use the datasource `Caused by: java.sql.SQLNonTransientConnectionException: [Macromedia][Oracle JDBC Driver]Server`.

I call the cfadmin in the browser and simply save the datasource without modifications. The line now reads 
```
"dsn":"jdbc:macromedia:oracle://XXXHOSTXXX:1521;SID=XXXSIDXXX;AuthenticationMethod=userIDPassword;sendStringParametersAsUnicode=false;querytimeout=0;MaxPooledStatements=100",
```
in the exported `.json`

What parameter do I have to set to get the hostname into the `dsn` string using `cfconfig`?

**Comment by bdw429s** [comment]
Hi Bernhard, I don't think you're doing anything wrong.  This looks like a
bug-- I think you're the first person to ever use the "datasource save"
command to create an Oracle datasource.  I have very little access to
Oracle so the Oracle stuff has received little testing.  Exporting and
importing Oracle datasources works because it uses the existing JDBC URL,
but creating a datasource from scratch is using the default JDBC URL baked
into CFConfig which had "server" hard coded on accident as well as a
hard-coded port.  Also, the default JDBC URL that I pulled from one of my
CF installs didn't have the SID=foo bit in there.  Can you tell me whether
all Oracle data sources will always have a SID, or is that an optional
thing?  I need to figure out how to make sure it's included when it needs
to be there.

The default JDBC URLs in CFConfig are specified like so:
"url":"jdbc:postgresql://{host}:{port}/{database}",

And then the {var} stuff is swapped out at run time with the actual values.

Thanks!

~Brad

*Developer Advocate*
*Ortus Solutions, Corp *

E-mail: brad@coldbox.org
ColdBox Platform: http://www.coldbox.org
Blog: http://www.codersrevolution.com

**Comment by bdw429s** [comment]
@bardware Also, can you confirm-- does Oracle not include the database anywhere in the JDBC URL?

**Comment by bdw429s** [comment]
@bardware Ok, please install the latest version of CFConfig and give this another test.
```
install commandbox-cfconfig --force
```
I just tested on an Adobe engine with the same command you post in the ticket above and this JDBC URL was created in the Adobe XML files:
```
jdbc:macromedia:oracle://XXXHOSTXXX:1521;SID=XXXSIDXXX;AuthenticationMethod=userIDPassword;sendStringParametersAsUnicode=false;querytimeout=0;MaxPooledStatements=100
```

**Comment by bardware** [comment]
This works. Thank you, Brad!
