### ISSUE TITLE
commandbox installation errors out

### ISSUE THREAD

**Issue by orcpac7** [Ortus-Solutions/cfconfig#13]
Running Commandbox 4.0.0 on Ubuntu, when I issue the command
``box install commandbox-cfconfig `
I get the error:
```ERROR (4.0.0+01015)
Error Cloning Git repository
java.lang.IllegalArgumentException: Invalid value: core.eol=lfw 
```
Can't find any clues on StackOverflow or Ortus-Solutions.com or the issue tracker for commandbox there.
FWIW, I'm running with Java jre1.8.0_51

**Comment by bdw429s** [comment]
Wow, that's a new one.  I can't say I've ever seen that but I was just
installing CFConfig yesterday.  I haven't specifically tried it on Ubuntu,
but I wouldn't expect that to matter since CommandBox's Git endpoint uses
jGit, a java Git library so it doesn't even use the native Git CLI.

Thanks!

~Brad

*Developer Advocate*
*Ortus Solutions, Corp *

E-mail: brad@coldbox.org
ColdBox Platform: http://www.coldbox.org
Blog: http://www.codersrevolution.com

**Comment by bdw429s** [comment]
Can you try this again and use the `--verbose` flag and report the output?
